#!/usr/bin/env bun

/**
 * Pre-build script: reads all files under agents/ and generates
 * lib/embedded-agents.ts so they are compiled into the binary.
 */

import fs from "node:fs";
import path from "node:path";

const AGENTS_DIR = path.join(import.meta.dir, "..", "agents");
const OUTPUT = path.join(import.meta.dir, "embedded-agents.ts");

interface FileEntry {
  relativePath: string;
  content: string;
  isBinary: boolean;
}

function collectFiles(dir: string, base: string): FileEntry[] {
  const entries: FileEntry[] = [];
  for (const item of fs.readdirSync(dir, { withFileTypes: true })) {
    const fullPath = path.join(dir, item.name);
    const relPath = path.relative(base, fullPath);
    if (item.isDirectory()) {
      entries.push(...collectFiles(fullPath, base));
    } else {
      const ext = path.extname(item.name).toLowerCase();
      const isBinary = [".sh"].includes(ext);
      const content = fs.readFileSync(fullPath, isBinary ? "base64" : "utf-8");
      entries.push({ relativePath: relPath, content, isBinary });
    }
  }
  return entries;
}

const files = collectFiles(AGENTS_DIR, AGENTS_DIR);

// Group by team
const teams = new Map<
  string,
  Map<string, { content: string; isBinary: boolean }>
>();
for (const f of files) {
  const teamName = f.relativePath.split(path.sep)[0] ?? "";
  if (!teams.has(teamName)) teams.set(teamName, new Map());
  teams
    .get(teamName)
    ?.set(f.relativePath, { content: f.content, isBinary: f.isBinary });
}

let code = `/**
 * Auto-generated by bundle-agents.ts — DO NOT EDIT.
 * Contains all built-in agent team files embedded for compiled binary use.
 */

export interface EmbeddedFile {
  content: string;
  isBinary: boolean;
}

/** team name → relative path → file content */
export const EMBEDDED_TEAMS: Record<string, Record<string, EmbeddedFile>> = {\n`;

for (const [teamName, filesMap] of teams) {
  code += `  ${JSON.stringify(teamName)}: {\n`;
  for (const [relPath, file] of filesMap) {
    code += `    ${JSON.stringify(relPath)}: { content: ${JSON.stringify(file.content)}, isBinary: ${file.isBinary} },\n`;
  }
  code += "  },\n";
}

code += `};\n\nexport const EMBEDDED_TEAM_NAMES = ${JSON.stringify([...teams.keys()])};\n`;

fs.writeFileSync(OUTPUT, code);
console.log(
  `✓ Embedded ${files.length} files from ${teams.size} team(s) → ${OUTPUT}`,
);
